---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 이미지를 넣어주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_abbc79fd6802
          workingDir: /workspace/runner
          command: ['sh', '-c', 'echo xxx && sleep 6000']
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-creds-5cfdm888b6
                  key: url.txt
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-creds-5cfdm888b6
                  key: username.txt
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-creds-5cfdm888b6
                  key: password.txt
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-creds-9fdcg6h8c4
                  key: jwt_secret.txt
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds-27gmf478g6
                  key: access_key.txt
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds-27gmf478g6
                  key: secret_key.txt
          resources:
            requests:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
