---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 이미지를 넣어주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_abbc79fd6802
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-creds-5cfdm888b6
                  key: url
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-creds-5cfdm888b6
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-creds-5cfdm888b6
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-creds-9fdcg6h8c4
                  key: jwt_secret
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds-27gmf478g6
                  key: access_key
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds-27gmf478g6
                  key: secret_key
          resources:
            requests:
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /api/test
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
