---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 이미지를 넣어주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_fde3606bc0cb
          command: ["sleep", "5m"]
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: database-url-b9dhc7d4dh
                  key: url.txt
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-creds-c76gbt99kb
                  key: username.txt
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-creds-c76gbt99kb
                  key: password.txt
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-creds-9fdcg6h8c4
                  key: jwt_secret.txt
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds-27gmf478g6
                  key: access_key.txt
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds-27gmf478g6
                  key: secret_key.txt
            - name: ACTUATOR_PORT
              valueFrom:
                secretKeyRef:
                  name: actuator-creds-26g454t96c
                  key: actuator_port.txt
            - name: ACTUATOR_PATH
              valueFrom:
                secretKeyRef:
                  name: actuator-creds-26g454t96c
                  key: actuator_path.txt
          resources:
            requests:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
