namespace: default
resources:
  - nginx.yaml
  - frontend.yaml
  - backend.yaml
  - mysql.yaml
configMapGenerator:
  - name: nginx
    files:
      - configs/default.conf
  - name: init-db
    files:
      - configs/init.sql
  - name: database-url
    files:
      - configs/url.txt
---
apiVersion: apps/v1
kind: Secret
secretGenerator:
  - name: database-creds
    files:
      - username.txt
      - password.txt
  - name: jwt-creds
    files:
      - jwt_secret.txt
  - name: aws-creds
    files:
      - access_key.txt
      - secret_key.txt
  - name: actuator-creds
    files:
    - actuator_port.txt
    - actuator_path.txt

