namespace: default
resources:
  - nginx.yaml
  - frontend.yaml
  - backend.yaml
  - mysql.yaml
configMapGenerator:
  - name: nginx-default
    files:
      - configs/default.conf
  - name: nginx-conf
    files:
      - configs/nginx.conf
  - name: database-url
    files:
      - configs/url.txt
secretGenerator:
  - name: database-creds
    files:
      - username.txt
      - password.txt
  - name: jwt-creds
    files:
      - jwt_secret.txt
  - name: aws-creds
    files:
      - access_key.txt
      - secret_key.txt
  - name: actuator-creds
    files:
      - actuator_port.txt
      - actuator_path.txt

