namespace: default
resources:
  - mysql.yaml
  - config.yaml
---
apiVersion: apps/v1
kind: Secret
secretGenerator:
  - name: database-creds
    files:
      - url.txt
      - username.txt
      - password.txt
  - name: jwt-creds
    files:
      - jwt_secret.txt
  - name: aws-creds
    files:
      - access_key.txt
      - secret_key.txt

